export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_FONT_FAMILY = 'CHANGE_FONT_FAMILY';
export const CHANGE_FONT_COLOR = 'CHANGE_FONT_COLOR';
export const CHANGE_BACKGROUND_COLOR = 'CHANGE_BACKGROUND_COLOR';
export const CHANGE_BACKGROUND_OPACITY = 'CHANGE_BACKGROUND_OPACITY';
